uwblueprint/rowan-house

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup.tsx
> adding town to frontend

- backend/graphql/resolvers/authResolvers.ts
- backend/graphql/types/authType.ts
- backend/graphql/types/userType.ts
- backend/models/user.model.ts
- backend/services/implementations/authService.ts
- backend/services/implementations/userService.ts
- backend/services/interfaces/authService.ts
- backend/types.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
Town property has been added to graphql types, typescript DTOs and resolvers. 
No further details as this is only an intermediate PR
> Added town field to backend

- backend/graphql/resolvers/authResolvers.ts
- backend/graphql/types/authType.ts
- backend/graphql/types/userType.ts
- backend/middlewares/validators/userValidators.ts
- backend/models/user.model.ts
- backend/services/implementations/authService.ts
- backend/services/implementations/userService.ts
- backend/services/interfaces/authService.ts
- backend/types.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
Adds a town field to the user signup page
Correctness of the data model on both create, update and read operations for users
- Test backend to ensure that api calls for users and authentication for create and read return a town property
- Test frontend to ensure that town property is in form and is updated correctly when input is changed
- E2E test frontend and backend to ensure that a user can be created with a given town name and the town name is returned when the user is queried for
Completed tests:
- As part of this ticket, I ran 2 quick tests locally. 1) Signup with a user, ensure that town property is in API request and saved in database. 2) Login with user, ensure that town property is returned as part of the model. Both tests passed. 
- Note that I didn't try and run a user query …
> Correct user signup input

- .github/pull_request_template.md
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- README.md
- backend/graphql/resolvers/lessonResolvers.ts
- backend/middlewares/auth.ts
- backend/middlewares/validators/lessonValidators.ts
- backend/middlewares/validators/userValidators.ts
- backend/models/entity.model.ts
- backend/models/index.ts
- backend/models/lesson.model.ts
- backend/server.ts
- backend/services/implementations/__tests__/userService.test.ts
- backend/services/implementations/courseService.ts
- backend/services/implementations/entityService.ts
- backend/services/implementations/lessonService.ts
- backend/services/implementations/userService.ts
- backend/services/interfaces/ILessonService.ts
- backend/services/interfaces/userService.ts
- backend/testUtils/testDb.ts
- frontend/.firebaserc
- frontend/package.json
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/EntityAPIClient.ts
- frontend/src/components/auth/Signup.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
- frontend/src/index.tsx
- frontend/yarn.lock
Ran linter, added chakra, started CICD
> Daniel's repo cleanup

- backend/graphql/index.ts
- backend/graphql/types/courseType.ts
- backend/graphql/types/userType.ts
- backend/models/course.model.ts
- backend/models/user.model.ts
- backend/services/implementations/__tests__/userService.test.ts
- backend/services/implementations/courseService.ts
- backend/services/interfaces/ICourseService.ts
- backend/types.ts
- frontend/src/types/AuthTypes.ts
- Updated document models & all course APIs to include the published and private attribute(s)
- Added a 3rd role called STAFF to the list of possible roles users can have
- Making sure the fields are added in the necessary locations, and that all the dependencies are met 
> Adding private and public fields

- frontend/src/APIClients/LessonAPIClient.ts
- frontend/src/APIClients/lessonAPIClient.ts
Adding a lesson api client! 
N/A
- ~~Do we need the `bearerToken` like in [EntityAPIClient](https://github.com/uwblueprint/rowan-house/blob/main/frontend/src/APIClients/EntityAPIClient.ts#L35-L42)?~~
- Ensure that request and response types are appropriate.
- Need to implement unit tests on all the methods
_- Need to implement better error handling_
> Implement Lesson API Client

- backend/graphql/resolvers/courseResolvers.ts
> Fix: failing getCourses request

- frontend/package.json
- frontend/yarn.lock
Self descriptive, docs here -- https://chakra-ui.com/docs/components/media-and-icons/icon#using-chakra-ui-icons
- Make sure to rebuild docker container
Does this properly add the dependency? Try adding an icon
- Additional dependencies/libraries you've added? => `@chakra-ui/icons`
> Add Chakra icons library dependency

- frontend/src/components/admin/CoursesOverviewTab.tsx
- frontend/src/components/pages/AdminDashboard.tsx
Display spinner on loading
Display "There are no courses" text instead of dummyData when there are no courses.
- 
> Fixes on CourseOverviewTab

- frontend/package.json
- frontend/src/components/common/content/ImageBlock.tsx
- frontend/src/components/common/content/TextBlock.tsx
- frontend/src/components/module-editor/BlockPreview.tsx
- frontend/src/components/module-editor/EditableContentBlock.tsx
- frontend/src/components/module-editor/LessonViewer.tsx
- frontend/src/components/module-editor/SideBarContentKiosk.tsx
- frontend/src/components/module-editor/SideBarModuleOverview.tsx
- frontend/src/components/pages/ModuleEditor.tsx
- frontend/src/index.css
- frontend/src/reducers/ModuleEditorContextReducer.ts
- frontend/src/types/ModuleEditorTypes.ts
- frontend/yarn.lock
Implementing the use of `react-beautiful-dnd` and make things start to work. Not concerned about visuals, just functionality.
- Play with it! See if there's anything weird (https://rowan-house-society--pr105-dnd-4u7je84p.web.app/admin/edit-module/test/module-hash-1)
- DnD library requires that every draggable item has a unique ID. I was thinking that these IDs could be added on initialization, and then removed when sending it back to the database. Should we do that or simply store the IDs?
- Added `react-beautiful-dnd`
- Based on [this implementation](https://github.com/atlassian/react-beautiful-dnd/issues/216#issuecomment-423708497) of copy drag
> Drag & Drop Skeleton

- backend/graphql/resolvers/courseResolvers.ts
- backend/graphql/types/courseType.ts
- backend/models/course.model.ts
- backend/services/implementations/courseService.ts
- backend/services/interfaces/ICourseService.ts
- frontend/src/APIClients/mutations/CourseMutations.ts
- frontend/src/APIClients/queries/CourseQueries.ts
- frontend/src/APIClients/types/CourseClientTypes.ts
- frontend/src/constants/DummyData.ts
- Reflect updated state of our documents (published attribute on modules, not courses) across models + interfaces + etc in backend
- Fix up course filtering for getCourse endpoint
- Filter through courses+modules for the following user/staff/admin access level logic:
```ts
case "User":
return {
includePrivateCourses: false,
includeOnlyPublishedModules: true,
};
case "Staff":
return {
includePrivateCourses: false,
includeOnlyPublishedModules: false,
};
case "Admin":
return {
includePrivateCourses: true,
includeOnlyPublishedModules: false,
};
```
- If `includedOnlyPublishedModules == true`, use aggregate query to unwrap module list, filter, and then return. Else use normal find query
- Using aggregate seems to prefer the explicit `_id` type and doesn't find the id string alias
Visual …
> Implement course/module visibility logic in course getters

- backend/graphql/resolvers/authResolvers.ts
In production, default accounts to the "User" role. Otherwise, default accounts to the "Admin" role.
N/A
- Is this implementation secure enough?
Test via creating a new user locally, then verifying that user has admin permissions.
> Update account default roles depending on the environment

- .github/CODEOWNERS
Auto-assign PRs to the PL as well as a random team member.
N/A
View results on future PRs.
Needs to be updated in future terms if this project gets future terms.
> Auto-assign PRs to the PL and a random other team member

- frontend/src/components/module-editor/SideBar.tsx
- frontend/src/components/module-editor/SideBarModuleOverview.tsx
- frontend/src/components/pages/ModuleEditor.tsx
- frontend/src/reducers/ModuleEditorContextReducer.ts
- frontend/src/types/ModuleEditorTypes.ts
- frontend/src/utils/lessonUtils.ts
> Function New Lesson Saving

- frontend/src/APIClients/BaseAPIClient.ts
- frontend/src/components/admin/EditCourseModal.tsx
- frontend/src/components/auth/Logout.tsx
Fix linter issues which were showing up on everyone's PR
- 
> Clean up linter issues on main

- backend/graphql/resolvers/authResolvers.ts
- backend/graphql/types/authType.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/mutations/AuthMutations.ts
- frontend/src/components/pages/VerifyEmail.tsx
Added ability to resend verification email in the event that old verification email has expired.
Default verify email page
Successfully re-sent verification email
Failed to send verification email
- Correctness of code
- Try going through the workflow and seeing if you can make it work successfully or make it error. See if anything can be broken.
- We should look to add explicit rate limiting
> [RHS-139] Add Verification Email Resend flow

- frontend/src/components/module-editor/content/EditableContentBlock.tsx
- frontend/src/reducers/ModuleEditorContextReducer.ts
Ability to delete content blocks
https://user-images.githubusercontent.com/36215359/177118715-54f01c51-b049-4c8c-8fe7-2cfa00d13739.mov
- Ability to delete content blocks, save your changes, and the updates be reflected.
- Delete a lesson, observe that it updates real-time
- Save your changes, refresh the page and see if it updates
- Observe you can create a content block, then delete it and no changes happen
> Deleting content blocks

- frontend/src/App.tsx
- frontend/src/components/admin/SideBar.tsx
- frontend/src/components/auth/LogoutButton.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/components/pages/Logout.tsx
- frontend/src/constants/Routes.ts
- frontend/src/hooks/useLogout.ts
- frontend/src/index.css
- frontend/src/theme/components/button.ts
- [RHS-117]: Extract logout button to new component
- Minor style fix for the logout button
- [RHS-117]: Add logout page
- 
Try to log out, verify it's intuitive and works.
N/A
> [RHS-117]: Fix main-page logout button

- backend/graphql/types/userType.ts
Fix missed type in User -> Learner migration.
N/A
- Can you find any other types (I couldn't)?
Tested by logging in locally, it does seem to work now.
This is why integration tests would be nice...
> Fix missing type in signup flow

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/theme/components/button.ts
The PR seeks to improve the login and signup flow. Refer to the ticket to see the list of things to fix for both pages. The login page now includes features like autofocus, autofill and error messages on login failure. The same also extends to the signup page. Previously, the signup page is in an error state by default, however, with this PR this only happens when a submission happens and there is actually an error. 
- Reviewers should ensure all the features/implementations work as expected and as described in the ticket.
- What ways could the input be wrong? Invalid Email / Password
- Is it secure? Could nefarious users access/break it? N/A
- Additional dependencies/libraries you've added? N/A
- Things …
> [RHS-190]: Login Flow Improvements

- frontend/src/components/module-viewer/LessonViewer.tsx
- frontend/src/components/module-viewer/ModuleViewer.tsx
- Module editor: contents should fill the entire screen
- Module editor: learner banner should be hidden in module editor
- 
> Module editor fixes

- backend/graphql/index.ts
- backend/graphql/resolvers/progressResolvers.ts
- backend/graphql/types/courseType.ts
- backend/graphql/types/progressType.ts
- backend/models/course.model.ts
- backend/models/courseProgress.model.ts
- backend/models/lessonProgress.model.ts
- backend/services/implementations/__tests__/progressService.test.ts
- backend/services/implementations/__tests__/userService.test.ts
- backend/services/implementations/progressService.ts
- backend/services/interfaces/ICourseService.ts
- backend/services/interfaces/IProgressService.ts
- frontend/src/APIClients/mutations/ProgressMutations.ts
- frontend/src/APIClients/queries/ProgressQueries.ts
- frontend/src/APIClients/types/CourseClientTypes.ts
- frontend/src/components/admin/CoursePreview.tsx
- Update module deletion to assign to null instead of removing
- Add course/lesson progress models and service
- Add course/lesson progress resolvers
Highly recommend reviewing by commit!
N/A
- Are the created endpoints useful?
- Are there use cases which are not handled by either the schema design or the query design?
Checkout locally, use Apollo extension to manually query endpoints.
N/A
> Course progress backend

- frontend/src/components/common/steps/Step.tsx
- frontend/src/components/common/steps/StepContext.tsx
- frontend/src/components/common/steps/StepIcon.tsx
- frontend/src/components/common/steps/StepSeparator.tsx
- frontend/src/components/common/steps/Steps.tsx
- frontend/src/components/common/steps/index.ts
Adds a `Steps` component to facilitate the epics being worked on by Matthew and Abubakar.
Usage:
```tsx
<Steps currentStep={1}>
{[0, 1, 2].map((index) => (
<Step
key={index}  // best not to use index as key in practice
index={index}
label={
<Heading as="h2" size="lg">
This is step {index + 1}
</Heading>
}
>
This is step {index + 1}.5.
{Array(2).fill(" The quick brown fox jumps over the lazy dog.")}
</Step>
))}
</Steps>
```
Playground (rough sketch of the components): https://codesandbox.io/s/chakra-ui-react-hook-form-forked-5q9cxk
- Code cleanliness, ease of use
Searched for libraries that implement this and didn't find any.
> Add step component

- frontend/src/APIClients/queries/ProgressQueries.ts
Add missing module progress query to frontend
N/A
- 
> Add module progress query

- backend/graphql/index.ts
- backend/services/implementations/authService.ts
- frontend/src/APIClients/mutations/AuthMutations.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/constants/Routes.ts
Implemented ability for users to reset password on the ui.
- By clicking forgot your password? on the login screen, you should be able to reset your password.
- If you enter a bad/invalid email, it will tell you 
- It will also tell you if it has successfully sent the link
- While send verification email is loading, you cannot spam click the button
- Click forgot your password
- Reset your password, wait for a email link to reset 
- Observe that you can reset your password
- Observe validation on your email is done, if you enter an invalid email it will error and alert you
> Create forgot-password flow

- backend/graphql/resolvers/progressResolvers.ts
- frontend/src/APIClients/types/ProgressClientTypes.ts
- frontend/src/components/module-viewer/ModuleCompleted.tsx
- frontend/src/components/module-viewer/NextModuleCard.tsx
- frontend/src/components/module-viewer/UpNext.tsx
We want to display a card on the module completion page indicating the up-next module.
- Testing user flow for viewing courses
- Check for different stages of module completion: (Not started, In Progress, Complete)
> Module Completion Page: Up Next

- backend/middlewares/validators/util.ts
- backend/types.ts
- frontend/src/APIClients/types/LessonClientTypes.ts
- frontend/src/assets/match.svg
- frontend/src/components/common/TextInput.tsx
- frontend/src/components/module-viewer/BlockPreview.tsx
- frontend/src/components/module-viewer/LessonViewer.tsx
- frontend/src/components/module-viewer/ModuleViewer.tsx
- frontend/src/components/module-viewer/SideBarContentKiosk.tsx
- frontend/src/components/module-viewer/content/blocks/MatchBlock.tsx
- frontend/src/components/module-viewer/content/blocks/index.ts
- frontend/src/components/module-viewer/content/helpers/ContentBlockTable.ts
- frontend/src/components/module-viewer/content/modals/EditMatchModal.tsx
- frontend/src/components/module-viewer/content/modals/index.ts
- frontend/src/reducers/ModuleEditorContextReducer.ts
- frontend/src/theme/foundations/colors.js
- frontend/src/types/ContentBlockTypes.ts
Adds match block component. Had to rework with ModuleViewer and LessonViewer to avoid nested DragDropContexts, but it all seems pretty good now! #197
Please make sure the following things work
- No match dragging while editing the lesson
- Editing the component on the admin side
- Using the component and checking the answer on the learner side
Test the learner side at https://rowan-house-society--pr238-matching-zjo8e69b.web.app/course/627864c6de32390004ab986b/1
> Matching Component

- frontend/src/APIClients/queries/LessonQueries.ts
- frontend/src/APIClients/types/LessonClientTypes.ts
- frontend/src/assets/halfComplete.svg
- frontend/src/components/common/steps/Step.tsx
- frontend/src/components/learner/ModuleDropdown.tsx
- frontend/src/components/learner/ModuleDropdowns.tsx
- frontend/src/components/learner/browser/CourseCard.tsx
- frontend/src/components/module-viewer/ModuleCompleted.tsx
- frontend/src/components/module-viewer/ModuleViewer.tsx
- frontend/src/components/module-viewer/UpNext.tsx
- frontend/src/components/pages/CourseOverview.tsx
- frontend/src/theme/components/text.ts
Implements the dropdowns from the Course Overview and Module Completion Pages
https://www.figma.com/file/hVyZkprXKN6myQuaIvRqfr/Learner-Views?node-id=663%3A8665
> Module Dropdowns for Course Overview and Module Completion Pages

- frontend/src/components/module-viewer/ModuleViewer.tsx
Addresses: https://github.com/uwblueprint/rowan-house/issues/239
Issue was dispatch was being performed inside a conditional when it shouldn't be. Simple fix
- 
> fixed completion of last lesson

- frontend/src/APIClients/types/ProgressClientTypes.ts
- frontend/src/components/pages/Default.tsx
Clicking the top tabs allows you to filter by started, in progress, and completed. Addresses https://github.com/uwblueprint/rowan-house/issues/216
https://user-images.githubusercontent.com/36215359/190315031-3c7eb6c9-9b67-40bb-bc3f-be2c1025add0.mov
Create 3 courses, and as a learner start one of them and finish another.
- Observe courses that have not been started are in not started
- Observe courses that have been started are in progress
- Observe courses than have been completed are completed
> Can filter by progress

- backend/graphql/index.ts
- backend/graphql/resolvers/courseResolvers.ts
- backend/graphql/types/courseType.ts
- backend/models/course.model.ts
- backend/services/implementations/courseService.ts
- backend/services/implementations/imageUploadService.ts
- backend/services/interfaces/ICourseService.ts
- frontend/src/APIClients/queries/CourseQueries.ts
- frontend/src/components/common/EditModuleModal.tsx
- frontend/src/components/module-viewer/SideBar.tsx
- frontend/src/components/pages/VerifyEmail.tsx
Display module images everywhere
- 
> Display module images everywhere

- frontend/src/APIClients/BaseAPIClient.ts
- frontend/src/components/module-viewer/BlockPreview.tsx
- frontend/src/components/module-viewer/ModuleViewer.tsx
- frontend/src/components/module-viewer/SideBarContentKiosk.tsx
- frontend/src/components/module-viewer/content/ContentBlock.tsx
- frontend/src/components/module-viewer/content/blocks/FlipCard.tsx
- frontend/src/components/module-viewer/content/blocks/MatchBlock.tsx
- frontend/src/components/module-viewer/content/blocks/column/ColumnBlock.tsx
- frontend/src/components/module-viewer/content/blocks/column/ColumnContent.tsx
- frontend/src/components/module-viewer/content/modals/EditButtonModal.tsx
- frontend/src/components/module-viewer/content/modals/EditHeadingModal.tsx
- frontend/src/components/module-viewer/content/modals/EditTextModal.tsx
- frontend/src/components/module-viewer/content/modals/EditVideoModal.tsx
> Editor niceties

- backend/graphql/resolvers/courseResolvers.ts
- backend/services/implementations/imageUploadService.ts
Check upload path and if it does not exist add it to prevent directory not found errors
- 
> add image folder

- frontend/src/components/common/VideoPlayer.tsx
- frontend/src/components/module-viewer/EditorTabs.tsx
- frontend/src/components/module-viewer/LessonItem.tsx
- frontend/src/components/module-viewer/ModuleCompleted.tsx
- frontend/src/components/module-viewer/ModuleViewer.tsx
- frontend/src/components/module-viewer/NextModuleCard.tsx
- frontend/src/components/module-viewer/SideBar.tsx
- frontend/src/components/module-viewer/SideBarModuleOverview.tsx
- frontend/src/components/module-viewer/content/ContentBlock.tsx
- frontend/src/components/module-viewer/content/blocks/MatchBlock.tsx
- frontend/src/components/module-viewer/content/blocks/QuizBlock.tsx
- frontend/src/components/module-viewer/content/blocks/TextBlock.tsx
- frontend/src/components/module-viewer/content/blocks/column/ColumnBlock.tsx
- frontend/src/components/module-viewer/content/blocks/column/ColumnContent.tsx
- frontend/src/index.css
- Make sidebar fill screen on smaller devices
- Adjust course padding depending on screen size
- Adjust size of videos to always fit on screen
- [unrelated bug]: Text blocks should not be editable
- Make module completion page responsive
- 
Manual testing on smaller screen sizes (can use devtools to easily try many sizes).
> Module viewer mobile support

- backend/package.json
- backend/yarn.lock
- frontend/src/APIClients/BaseAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/components/module-viewer/SideBar.tsx
- Sign up cosmetics
- Refresh token error quick-fix
- Module saving toasts
> Ally's bug fixes
