uwblueprint/rowan-house

backend/graphql/types/authType.ts
backend/services/implementations/userService.ts
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/components/auth/Login.tsx

Since we already removed some parts of google auth in a past PR, Emma suggested I delete it from the frontend auth service, at which point I figured I'd just nuke Google Auth from the codebase. Perhaps it's because I hold a grudge from them rejecting my application, but it saves us work down the line. The google auth code still exists in start code in case we want to reuse the design pattern.
Login screen with no google auth:
- That this didn't break anything else in auth
- Try logging in, logging out, signup, other auth operations. 
- Completed tests: I've already tried singing up, then logging in, then logging out, seems to work fine.

Remove Google Auth

---

backend/services/implementations/courseService.ts

Found a bug on the `UpdateCourse` mutation -> calls `id` property of passed course, which doesn't exist. Get from result returned from db instead
- Change from prev PR, this comment -> https://github.com/uwblueprint/rowan-house/pull/21#discussion_r795252898
- Makes sense? 
See testing section in https://github.com/uwblueprint/rowan-house/pull/21
- Additional dependencies/libraries you've added? None
- Things you'd want to know when coming back to the code after a few months Nothing new

Fix updatedCourse mutation return bug where id not on argument

---

backend/services/interfaces/userService.ts
utils.sh

Linter had suggestion in previous PR that I didn't touch, this fixes it and also adds a bash script that runs the linter in the backend with auto fix
n/a
- Check that the command runs properly on your computer -> `bash util.sh lint`
Think just run it
- Additional dependencies/libraries you've added? nope
- Things you'd want to know when coming back to the code after a few months -> can add more things to utils.sh as common commands happen

Find linter error and add bash command to run linter

---

backend/graphql/index.ts
backend/graphql/resolvers/lessonResolvers.ts
backend/graphql/types/lessonType.ts
backend/services/implementations/lessonService.ts
backend/services/interfaces/ILessonService.ts

Added create and delete mutations for lessons!
N/A Backend work
- Does this align with how we want to add new APIs? Are we relying properly on the entity example?
- Are the correct fields marked optional?
Testing procedure:
- Go to <backend-url>/graphql, for me this is [http://localhost:5000/graphql](http://localhost:5000/graphql)
- Try out queries and mutations. Include some mutations that don't have default values included (eg. no description):
Mutation 
```
mutation{
// create a lesson
createLesson(lesson: {
course: "ID",
title:"Lesson 1",
description:"this is a description",
image:"https://picsum.photos/536/354",
content: [""],
}) {
id,
course,
title,
description,
image,
content,
}
}
// change a parameter
updateLesson(id: string, lesson: {
course: "ID",
description:"this is a modified …
```

Implement Lesson API - Create and Delete

---

backend/graphql/index.ts
backend/graphql/resolvers/userResolvers.ts
backend/graphql/types/userType.ts
backend/services/implementations/userService.ts
backend/services/interfaces/userService.ts

Rowan house wants to be able to query information about their users -- one such query is number of users per town, limited by a start and end date
- Uses objectId timestamps, autogenerated instead of creating our own field. Docs here -> https://docs.mongodb.com/manual/reference/method/ObjectId.getTimestamp/
- Returns JSON string (`"{\"Toronto\":2,\"Vancouver\":1}"`) which is easily understood and can be parsed
- However, this is not labelled as town / userCount so please comment on whether it's clear and usable
- Future improvement in frontend -- limit input selection to prevent typos, etc.
Visual depiction of PR **n/a**
- Does return format make sense?
- Do we need further granularity than `yyyy/mm/dd`?
- No frontend work in this ticket?
- What test(s) should we run to make sure your …

Implement aggregate user count by town query

---

backend/graphql/resolvers/courseResolvers.ts
backend/graphql/types/courseType.ts
backend/services/implementations/courseService.ts
backend/services/interfaces/ICourseService.ts

Result of discussion on separate DTO objects on create and update mutations -- want separate so that we can be clear which params are required on create vs. required for an update (not the same)
n/a not frontend
- Missing any instances?
- Required params makes sense?
- See testing section in https://github.com/uwblueprint/rowan-house/pull/21
- Rebase will be needed, either on this one, or on https://github.com/uwblueprint/rowan-house/pull/50 
- Was going to hold off on this one until #50 merges

Separate create and update course DTO objects for required params clarity

---

backend/graphql/resolvers/courseResolvers.ts
backend/models/course.model.ts
backend/services/implementations/authService.ts
backend/services/implementations/courseService.ts
backend/services/interfaces/ICourseService.ts
backend/services/interfaces/authService.ts
backend/utilities/errorUtils.ts

Separates access to courses between (User) and (Staff, Admin):
- users only have access to courses marked `private: false` and `published: true`
- staff/admin have access to all courses
Changes resolver to fulfill with appropriate logic
- Chatting with internal tools about this approach -- https://uwblueprint.slack.com/archives/C021C0R7KM2/p1645989506184349
- Is this the right separation of logic across layers?
Not sure how to test at the moment since no test admin users... should check that it filters as expected for various combinations of `private` and `published` attributes
- Things …

Limit access to courses based on role and private/published attributes

---

frontend/src/theme/components/index.ts
frontend/src/theme/components/text.ts
frontend/src/theme/index.ts
utils.sh

Initial few changes for course block ticket
- Only separating this into its own ticket to make sure the text stylings are available for all future frontend work (and so no duplication on this work)
- Please compare to the Figma -> https://www.figma.com/file/zh6zk2LJo0RodIHBVycylC/RHS-Design-System?node-id=217%3A9061
- All styles should align exactly with values in `text.ts`
- What the heck is the `em` property supposed to be 
Utils script should be manually testable
-> on Mac, command is `bash utils.sh felint` // `bash utils.sh belint`
-> may not work on other platforms
- Things you'd want …

Add custom text variants/styles, utils command for linting

---

frontend/src/APIClients/CourseAPIClient.ts

Adding a course api client!
N/A
- Ensure that request and response types are appropriate.
Steps to test:
1. Checkout branch [testing-course-api-client](https://github.com/uwblueprint/rowan-house/tree/testing-course-api-client); note - this branch was created from the course-api-client branch
2. Log in and change route to `/dummy`. (Open dev tools console to see console log statements)
3. Press the create button to create a course with the parameters in [lines 78-86](https://github.com/uwblueprint/rowan-house/commit/8355f9775db851c960dfc7dad89dc2f31caace60#diff-b73a84f2d8afa5dcb756949b432c36a1bb90adcf309ea9ce66337d02c9e74903R78-R86) of the Dummy component 
4. Refresh the page to see that the course has been created
5. To test the update method, access mongodb atlas and retrieve the id of …

Implement Course API Client

---

backend/graphql/resolvers/courseResolvers.ts
backend/graphql/types/courseType.ts
backend/models/course.model.ts
backend/services/interfaces/ICourseService.ts
frontend/src/APIClients/types/CourseClientTypes.ts
frontend/src/App.tsx
frontend/src/components/admin/CoursePreview.tsx
frontend/src/components/admin/CoursesOverviewTab.tsx
frontend/src/components/admin/ModulePreview.tsx
frontend/src/components/module-editor/SideBarModuleOverview.tsx
frontend/src/components/pages/ModuleEditor.tsx
frontend/src/constants/DummyData.ts
frontend/src/reducers/ModuleEditorContextReducer.ts
frontend/src/types/AdminDashboardTypes.ts
frontend/src/types/ModuleEditorTypes.ts

There were a lot of files edited, but the main points are:
- Modules should now be a list of objects instead of a map
- Module Editor URL now uses the index of the module as the identifier for which module is being edited
- Response DTOs can now have null attributes to prevent GraphQL errors from occuring
Same as before, not applicable.
- Should the URL of the module editor use the index of the array or still its ID?
- Make sure the admin dashboard still works!

Converting modules to an array, allow null response

---

frontend/src/APIClients/BaseAPIClient.ts
frontend/src/APIClients/types/CourseClientTypes.ts
frontend/src/components/admin/CoursePreview.tsx
frontend/src/components/admin/EditCourseModal.tsx
frontend/src/components/admin/EditModuleModal.tsx
frontend/src/components/admin/ModulePreview.tsx
frontend/src/components/common/DeleteModal.tsx
frontend/src/components/common/Modal.tsx
frontend/src/components/common/SwitchInput.tsx
frontend/src/components/common/TextArea.tsx
frontend/src/components/common/TextInput.tsx
frontend/src/components/pages/ManageCoursesPage.tsx
frontend/src/types/AdminDashboardTypes.ts
frontend/src/types/ComponentTypes.ts

Implements landing Page: Modals #64 
Implements modals to edit and create courses and modules, and to confirm deletes of courses/modules. Does not include backend calls to submit forms, or photo uploading for edit module modal.
Components added:
- DeleteModal.tsx: base delete modal (can be reused for different deletion purposes)
- Edit Course/Module Modals: specific modals for editing courses and modules
Common:
- TextInput.tsx: component for user input in forms (based off Chakra UI input)
- TextArea.tsx: component for user input more than one line (based off Chakra UI TextArea)
- SwitchInput.tsx: based off Chakra UI switch
- Modal.tsx: base modal component (based off Chakra UI Modal)
Still needs to be implemented:
- photo uploading for module editing
- error messages and states for when …

Admin Dashboard Modals

---

frontend/src/components/module-editor/EditContentOptionsMenu.tsx
frontend/src/components/module-editor/EditableContentBlock.tsx
frontend/src/theme/components/button.ts
frontend/src/types/ModuleEditorTypes.ts

Note: I'm still unhappy with the padding on the left side (when you hover, you can see that the divider doesn't extend fully to the left, because of the sidebar). Not blocking and high-priority, but little fix TODO. Similar for padding between buttons, it seems to force a width on the icon button
- Add icon buttons to each content block, for edit, copy, and delete options
- Dummy buttons right now (not doing anything)
https://user-images.githubusercontent.com/40974372/169189856-4cd88946-f7de-4ce6-a846-b8a6ad435c28.mov
Compare to [figma](https://www.figma.com/file/Dimm13cjrpYU5LkcrV6VxF/Course-Editor?node-id=691%3A3296):
- slight changes to the icons used (used the default Chakra icons)
- check spacing? I matched the Figma but will double check because it looks different
- What's the right …

Add edit/copy/delete buttons on content block hover

---

backend/services/implementations/courseService.ts

Details: Depending on whether a user is a User or an Admin, we fetch courses from the DB in different ways. Either we fetch them using find (Admins) or using aggregate (Users). However, results from an aggregation are missing the .id field by default, which causes GraphQL queries which expect that field to fail (see [this issue](https://github.com/Automattic/mongoose/issues/8784)).  To fix this, we can pass the aggregation results through MgCourse.hydrate, which will populate the expected fields.
N/A
- 
- What test(s) should we run to make sure your code works? Set a user to the "User" role in Mongo, then load the admin homepage `/admin/courses`. If there's no crash, this fix is working.
- What ways could the input be wrong? N/A
- Is it secure? Could nefarious users access/break it? See …

[RHS-145]: Fix user access to list courses endpoint

---

.gitignore
.vscode/launch.json
backend/nodemon.json
docker-compose.yml

A feature for the development environment requested by devs was to be able to connect to the frontend/backend via a debugger. This PR adds some configuration to the repository to support this.
- [RHS-173]: Enable debug mode for node while developing
- [RHS-173]: Add launch configurations for devs using VS Code
N/A
- How do you feel about permanently running in `--inspect` mode for all local development? Is it worth it in order to prevent having to commit a `settings.json` with extra command configuration?
Feel free to check this out locally and try it yourself. The normal development flow is unchanged (run `docker-compose up --build`), but you should be able to run additional debug configurations from the tab on the left-hand side of VS Code.
N/A

[RHS-173]: Enable debugging

---

frontend/src/components/module-editor/EditContentOptionsMenu.tsx

As the title says, per designer feedback, the content edit/delete buttons in the module editor should be top-aligned rather than centre-aligned.
Before:
After:

Editor content edit buttons should be top aligned

---

.gitignore
.pre-commit-config.yaml
docker-compose.yml
frontend/package.json
scripts/launch_dev.sh
scripts/lint.sh
utils.sh

- Hint at devs to install pre-commit on docker startup
- Lint on pre-commit
- Use linter cache to speed up pre-commit hooks
- Can you think of cleaner/faster ways to implement this?
A: Not designed to be secure, only hint to install pre-commit hooks for users.

[RHS-158]: Add linter pre-commit hooks

---

.gitattributes
backend/graphql/index.ts
backend/middlewares/auth.ts
backend/middlewares/utils/combinatorsUtils.ts
backend/services/implementations/authService.ts
backend/services/interfaces/authService.ts
frontend/src/components/admin/UserCard.tsx

A follow-up to https://github.com/uwblueprint/rowan-house/issues/136. A logged-in user should not be able to change their own role. There is a frontend and backend implementation to this ticket. The frontend implementation ensures that the edit role button in the `Manage Users` page does not appear when the logged-in user is searched for. The backend implementation acts as a sanity check to ensure a similar functionality. 
- Ensure that if a logged-in user searches their name on the  Manage Users page, the edit button does not appear in the user card that appears on the page.
- Logged-in admin users should be able to change the user role of other users on the application. 
- Is it secure? …

[RHS-179] : Prevent Users from Changing their Role

---

backend/graphql/index.ts
backend/graphql/resolvers/authResolvers.ts
backend/graphql/resolvers/courseResolvers.ts
backend/models/user.model.ts
backend/services/implementations/__tests__/userService.test.ts
backend/services/implementations/userService.ts
backend/types.ts
e2e-tests/test_auth.py
e2e-tests/test_auth_gql.py
e2e-tests/test_user.py
e2e-tests/test_user_gql.py
frontend/src/constants/UserConstants.ts

Closes #149.
From the ticket:
The name `User` is ambiguous and doesn't match the mockups. We should use the terminology `Learner` instead.
N/A
- Do you see any side effects of this change _other than_ breaking the dev environment?
- Are there any usages you can think of which wouldn't have been found by just searching for `"User"`?
- Play with the local environment.
Will not merge this until Monday's work session so that we can (hopefully) notify more devs of the change.

[RHS-149]: User -> Learner migration

---

backend/graphql/index.ts
backend/graphql/resolvers/courseResolvers.ts
backend/graphql/resolvers/lessonResolvers.ts
backend/graphql/types/lessonType.ts
backend/middlewares/auth.ts
backend/services/implementations/authService.ts
backend/services/implementations/lessonService.ts
backend/services/interfaces/ILessonService.ts
backend/services/interfaces/authService.ts

- Make course info API routes public
- Add new public route returning minimal lesson information
The commits are disjoint so I'd recommend reviewing by commit.
N/A
- Is the logic secure?
- Does the new route cover all remaining use cases for public lesson info?
Checkout branch and try GQL endpoints as a non-logged-in user.
None

Make course/lesson info API routes public

---

frontend/src/APIClients/AuthAPIClient.ts
frontend/src/APIClients/BaseAPIClient.ts
frontend/src/utils/AuthUtils.ts

- Update GraphQL error logging code to be more useful to devs
- Update BaseAPIClient token injection to refresh if necessary
The crux of the issue was that with Firebase, we're supposed to refresh our access tokens every hour, but we weren't doing that at all. This PR updates our GraphQL client so that any request with an expired token will request a new token before the request goes through.
The PR also greatly improves the GraphQL logging logic to help devs with debugging. Since the PR includes this secondary debugging fix, I'd recommend reviewing by commit.
- Is the code clean and well-structured?
- Is this scheme secure?
Two options:
1. If you're only planning on testing once (risky since you may have to wait an hour each time you want to re-test):
1. Open the preview URL, log in with …

Fix 1h account logout issues

---

.pre-commit-config.yaml
backend/graphql/types/lessonType.ts
backend/middlewares/validators/util.ts
backend/services/implementations/lessonService.ts
backend/types.ts
frontend/src/APIClients/mutations/LessonMutations.ts
frontend/src/APIClients/queries/LessonQueries.ts
frontend/src/components/common/CustomHeading.tsx
frontend/src/components/common/content/HeadingBlock.tsx
frontend/src/components/common/content/index.ts
frontend/src/components/learner/ModuleLessonCount.tsx
frontend/src/components/module-viewer/content/ContentBlock.tsx
frontend/src/components/module-viewer/content/modals/EditHeadingModal.tsx
frontend/src/components/module-viewer/content/modals/index.ts
frontend/src/components/pages/CourseOverview.tsx
frontend/src/reducers/ModuleEditorContextReducer.ts
frontend/src/types/ContentBlockTypes.ts
frontend/src/types/CourseOverviewTypes.ts
frontend/src/types/ModuleEditorTypes.ts

Added heading component to lessons, customizable text and size. This allows RHS to break their lessons into blocks
- Ability to create a heading component, change the text, and the size
- By default (if no text is provided), the preview will just say heading.
- If no text is entered and someone tries to submit, it will fail
- After saving, you can refresh and see that the changes are still there
- Create a heading component
- Change the size, and the text.
- Observe if you change text to be empty it will fail to save
- Observe after submitting but before saving changes the changes are shown
- Observe that after saving changes, refreshing the page, the changes still exist.

Heading component

---

frontend/src/APIClients/BaseAPIClient.ts

We were refreshing the auth token for signup endpoints due to a naming issue, which caused auth errors. This PR migrates `SignUp` -> `Signup_Register`.
N/A
- 

Fix mismatched endpoint name for Signup

---

backend/graphql/index.ts
backend/graphql/resolvers/courseResolvers.ts
backend/graphql/types/courseType.ts
frontend/src/APIClients/BaseAPIClient.ts
frontend/src/APIClients/queries/CourseQueries.ts
frontend/src/components/learner/browser/CourseCard.tsx
frontend/src/components/pages/Default.tsx

Load in real courses as opposed to dummy data on the courses view page.
- Make sure that real courses are now being displayed at the root URL (localhost:3000)
- Create some courses, note the title and the description
- Observe that when you go to the root URL this is what is being displayed

display real courses

---

frontend/src/components/common/SaveModal.tsx
frontend/src/components/module-viewer/SideBar.tsx

The PR seeks to implement a new mechanism for users to save their made changes on the module editor page when they decide to exit. When users click on the back button to go back to the course overview page, a modal pops up asking if they want their changes saved, unsaved, or canceled. The different behaviors of these choices are documented in the ticket linked to this PR. 
- Ensure the modal buttons work as described in the ticket.
- Ensure when no changes are made, the back button successfully routes to the appropriate page.
- Test the functionality for both admin and learners. 
- Things …

[RHS-144] - Module Editor: Prevent Losing Progress Modal

---

frontend/src/APIClients/queries/UserQueries.ts
frontend/src/APIClients/types/UserClientTypes.ts
frontend/src/components/admin/DatePicker.tsx
frontend/src/components/admin/DownloadDataModal.tsx
frontend/src/components/common/Modal.tsx
frontend/src/components/pages/ManageUsersPage.tsx

Added a modal for downloading and added the date pickers as a separate component. The apollo hook used is the `useLazyQuery` hook since we only want to query the data when the user clicks download.
- Downloading is disabled until a complete date range is provided OR `download all data` is selected
- An invalid date range shows an error
- Non numeric characters do not appear in the year input
- Testing
- Follow the issue #137 for info on what the expected behaviour should be.
- Test that download button is only disabled if you are selecting specific date ranges, but have not provided all date range info
- Test that an error shows up if the start date is later than the end date
- Test that closing the modal and returning to it will start in a fresh state
- Things you'd want to know when …

add modal for downloading user stats

---

frontend/src/components/learner/browser/CourseCard.tsx
frontend/src/components/learner/browser/CourseTabs.tsx
frontend/src/components/module-viewer/LessonItem.tsx
frontend/src/components/pages/CourseOverview.tsx
frontend/src/components/pages/Default.tsx
frontend/src/components/pages/VerifyEmail.tsx
frontend/src/theme/index.ts

- Fix style of lesson items
- Adjust spacing on homepage to support 2-line titles
- Make homepage responsive
- Make course overview page semi-responsive
See preview URL.
- Do the fixes work as expected?
Open the preview URL, and go through the changes listed above. Verify that the pages work as expected. For checking responsiveness, you can use Chrome's devtools and press Ctrl-Shift-M to change the device. Also verify the pages still look "good" on desktop.
Did not get to making the module editor responsive, this will probably be a larger undertaking. For responsiveness, the goal was to make learner-facing things responsive, since admins will likely be using a computer.

Style fixes

---

backend/graphql/index.ts
backend/graphql/resolvers/courseResolvers.ts
backend/graphql/types/courseType.ts
frontend/src/APIClients/mutations/CourseMutations.ts
frontend/src/components/admin/CoursePreview.tsx
frontend/src/components/admin/EditCourseModal.tsx
frontend/src/components/admin/ModulePreview.tsx
frontend/src/components/common/EditModuleModal.tsx
frontend/src/components/learner/browser/CourseCard.tsx
frontend/src/components/module-viewer/ModuleCompleted.tsx
frontend/src/components/module-viewer/NextModuleCard.tsx
frontend/src/components/module-viewer/SideBar.tsx
frontend/src/components/module-viewer/UpNext.tsx
frontend/src/components/pages/CourseOverview.tsx

You can now add images to courses themselves, and they are the default images for the course modules if there are no course module images set
https://user-images.githubusercontent.com/36215359/194804032-8b787456-3df0-4341-aed3-2c40d1dc7ade.mov
- you can edit/create a course, and upload an image by clicking save in the edit modal 
- The image should persist
- Create a new course, create some modules in that course
- Upload an image
- Ensure you can see that image in the course preview 
- Ensure that you can see that image when you submit the course image, and that refreshing still contains it

course support for images

---

frontend/src/components/module-viewer/SideBar.tsx
frontend/src/reducers/ModuleEditorContextReducer.ts
frontend/src/theme/components/button.ts

- Don't show save button when new block is cancelled
- Buttons shouldn't disappear on hover when loading/disabled
- Add loading spinner to save button
No big visual changes, changes occur on interaction
- 
Manual testing: add content to the lesson, and check if saving works as expected.
Manual testing: hover over a disabled/loading button.

Style improvements while loading
